### PR TITLE
Updated dependencies for Debian/Raspbian Buster

### PR DESCRIPTION
**Pull request by ItalyPaleAle**
Debian 10 (Buster) is coming out soon and will have some packages named differently. Raspbian Buster is already out.

Tested on Buster on a RPi

### CODE REVIEW

**Comment by TingluoHuang** [comment]
Thanks for heads up, I will merge the PR after dotnet core ship a version that supports Debian 10.

**Comment by ItalyPaleAle** [comment]
@TingluoHuang .NET Core supports Buster now: https://github.com/dotnet/core/issues/3051 Any chance you could merge this? 

My eagerness comes from the fact that I need this to run the agent on a RPi 4 :)

**Comment by serbrech** [comment]
I've been trying to run an agent on a buster based image FYI: 
https://github.com/dotnet/corefx/issues/33179#issuecomment-528911543

**Comment by damccorm** [comment]
Sorry for the slow response here - looks like these changes got added separately in a different PR!

**Pull request closed without merging**
