### PR TITLE
Set up schedule and notifications for the localization pipeline

### PR DESCRIPTION
**Pull request by egor-bryzgalov**
**Task name**: Localization pipeline definition

**Description**: 
Added schedule trigger to run the localization pipeline on the third week of a sprint on Mondays at 8 a.m. UTC,
Added Slack notifications about successful and failed builds.
Added a script that automatically bumps tasks and common packages versions.
Added a script that creates a PR to the master branch with localization updates.

The pipeline is going to have the following flow:
Checkout Localization branch -> merge master into Localization and push changes -> OneLocBuild task gathers localization strings and commits them (auto-merge a PR) to the Localization -> create a new branch with localization updates -> open a PR to the master branch.

**Documentation changes required:** No

**Added unit tests:** No

**Attached related issue:** [#878](https://github.com/microsoft/build-task-team/issues/878)

### CODE REVIEW

**Comment by EzzhevNikita** [comment]
@egor-bryzgalov Is it normal that the OneLocBuild step is failing for now on CI?

**Comment by egor-bryzgalov** [comment]
> @egor-bryzgalov Is it normal that the OneLocBuild step is failing for now on CI?

Yes. It fails when invoked for another branch except `Localization`.

**Review by EzzhevNikita — APPROVED** [review]
LGTM!

**Review by anatolybolshakov — APPROVED** [review]

**Comment by egor-bryzgalov** [comment]
[Successful build.](https://dev.azure.com/mseng/PipelinesLocalization/_build/results?buildId=14599734&view=logs&j=3b94f880-87f8-584e-4049-e95fdb9e35af&t=77f70620-4502-5e17-282e-f9b935940211)

**Review by alexander-smolyakov — APPROVED** [review]

**Review by EzzhevNikita — APPROVED** [review]

**Review by anatolybolshakov — APPROVED** [review]

**Pull request merged**
