### PR TITLE
Minimal support for SELinux in svc.sh

### PR DESCRIPTION
**Pull request by catatonicprime**
Corrects Issue #2738 

There is some confusion about the importance of hypen/dash characters in the service name. I don't believe these have significant impact on functionality only perhaps on readability after escaping to '\x2d'

I've tested this with a minimal install of CentOS 8 where SELinux is enabled by default.

Special thanks to the original issue posters; I was probably about to spend too many days on this forgetting SELinux was even a thing :laughing: 

Edit0: I may have opened this too soon - I was just trying to get my agent running/executing. I see now in the original issue there may be *additional* SELinux corrections that need to be made.

Edit1: I've successfully verified that at least *some* build functionality is capable using the standard starter pipeline. I think an additional issues around SELinux may need to be resolved separately through additional systems administration separate from installing the service itself (what this fixes).

Also, sorry I wasn't sure which branch to attempt the PR to - please feel free to shuffle anything around that I may have derp'd over.

My yaml pipeline used to execute:
```
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: 'linux-agents'

steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'
  
  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
```

### CODE REVIEW

**Comment by vtbassmatt** [comment]
This will fail on any system without the `sestatus` command.

**Comment by catatonicprime** [comment]
Oh yeah, good catch.

Now... How to fix it properly...

**Comment by catatonicprime** [comment]
I think 'which' is always available, so hopefully this is sufficient. We use which to verify the command is in the path & can be used before checking the SELinux status.

I should get out of homogeneous systems more. Very nice catch.

**Comment by vtbassmatt** [comment]
`command -v` would be slightly broader... there's at least one major distro (maybe Alpine?) that doesn't have `which`.

**Comment by catatonicprime** [comment]
If you're in bash, which we are, that's a slick trick. Thanks for the tip. Logic remains the same.

**Comment by vtbassmatt** [comment]
I think `command` might even be POSIX-y. Anyhow, yes, we have LOTS of `bash` dependencies (woe be unto us). Anyhow, now that we have that out of the way, @mjroghelia do you see any harm in merging this? It doesn't change our official stance on SELinux (which is that we neither support nor block it) but probably makes SELinux users' lives better.

**Comment by catatonicprime** [comment]
Heh, yeah, I realized it may be mor generic than bash. Also I'd like to apologize, I said bash & I later realized this is a friction topic; it wasn't my intent to poke or prod the subject really just wanted to focus on the great tip about the command & pattern. Thank you for it, makes me a better system developer.

**Comment by vtbassmatt** [comment]
No worries, and I replied that way because frankly I'm not even sure. Mostly leaving it as a trail of breadcrumbs for anyone who finds this thread later!

**Pull request merged**
