### PR TITLE
Bumping vss-api-netcore version to 0.5.127-private for the DPAproxy fix

### PR DESCRIPTION
**Pull request by fadnavistanmay**

### CODE REVIEW

**Comment by fadnavistanmay** [comment]
FYI - @johnterickson @owenhuynMSFT

**Comment by fadnavistanmay** [comment]
@TingluoHuang

**Comment by TingluoHuang** [comment]
@fadnavistanmay PR build failed.

**Comment by fadnavistanmay** [comment]
> @fadnavistanmay PR build failed.
Looking into it.

**Comment by johnterickson** [comment]
Looks like it does need my fallback changes.

**Comment by johnterickson** [comment]
Some of it that is.

**Pull request closed without merging**
