### PR TITLE
More configurations to knobs and make preferPowerShellOnContainers true by default

### PR DESCRIPTION
**Pull request by damccorm**

### CODE REVIEW

**Comment by damccorm** [comment]
Updated to prefer PowerShell on windows containers. This should fix https://github.com/microsoft/azure-pipelines-agent/issues/2870

Decided to do this after some offline conversation with Tommy to get context, see https://github.com/microsoft/azure-pipelines-tasks/issues/11448#issuecomment-610619531 for full context on why we made this decision.

**Comment by Automobileservices4** [comment]
#2913

**Comment by Silvenga** [comment]
@damccorm is there an estimated release time for this fix?The breaking change of `preferPowerShellOnContainers = false` is breaking a lot of our builds with the agent released on Azure DevOps.

**Comment by mjroghelia** [comment]
@Silvenga We expect to make the next release with this fix toward the end of next week.

**Pull request merged**
