### PR TITLE
Remove Node 14

### PR DESCRIPTION
**Pull request by alex-peck**
Remove Node 14 binaries and handler to reduce package sizes since we are moving forward with Node 10

### CODE REVIEW

**Comment by damccorm** [comment]
We should probably do the same with everything else in this pr - https://github.com/microsoft/azure-pipelines-agent/pull/3103/files. I'm personally more inclined to just rip out all Node 14 related work for now - I think it'll confuse the code base (especially important if we're handing it off) and I'm fairly convinced Node 14 won't be current LTS by the time we get off Node 10

**Comment by alex-peck** [comment]
> We should probably do the same with everything else in this pr - https://github.com/microsoft/azure-pipelines-agent/pull/3103/files. I'm personally more inclined to just rip out all Node 14 related work for now - I think it'll confuse the code base (especially important if we're handing it off) and I'm fairly convinced Node 14 won't be current LTS by the time we get off Node 10

Ahh, you're probably right... I'll keep around the changes that will make it easier to upgrade in the future but get rid of references to Node 14.

**Comment by mjroghelia** [comment]
This needs to go too: https://github.com/microsoft/azure-pipelines-agent/blob/master/.azure-pipelines/signing.yml#L157

**Comment by alex-peck** [comment]
> This needs to go too: https://github.com/microsoft/azure-pipelines-agent/blob/master/.azure-pipelines/signing.yml#L157

It is already gone. See "signing" commit

**Review by mjroghelia — APPROVED** [review]

**Comment by SimonAlling** [comment]
> As I understand it, only Node 6 and Node 10 are available to run tasks right now. Both of these are now EOL: https://endoflife.date/nodejs
> 
> Is there a planned date when Node 14 or 16 might become available for use?

Ironically (as I just found this issue), "Active Support" even for Node **14** "ended _today_ (19 Oct 2021)" according to the linked page.

Being able to write tasks against a newer version of Node would definitely be appreciated, not least because of better syntax and standard-library support.

**Pull request merged**
