### PR TITLE
Fix custom lfs

### PR DESCRIPTION
**Pull request by tmisch**
Fix support of external `git lfs` repository by checking out file `.lfsconfig` before running `git lfs fetch`.

### CODE REVIEW

**Comment by jtpetty** [comment]
@tmisch - I have not forgotten about this. We needed to get a few other things in and I have not had time to circle back to this. I had made an attempt to get rid of the duplicate classes that perform git functions to make this update a little easier, but that effort has also stalled for me.

**Comment by tmisch** [comment]
@jtpetty - Thanks for letting me know what's going on. I thought that the PR was stuck because of the unit test failure that is fixed meanwhile.

**Comment by anatolybolshakov** [comment]
Tested locally - LGTM, thanks!

**Comment by tmisch** [comment]
@anatolybolshakov and you for taking over. good luck

**Pull request closed without merging**
