### PR TITLE
remove all the preview docs

### PR DESCRIPTION
**Pull request by vtbassmatt**
All the core YAML docs have been moved to docs.ms.com. Eric and I agreed to remove the preview docs now. If there are topics that haven't been migrated to docs.ms.com, we can delve into GitHub history and push them over.

### CODE REVIEW

**Comment by vtbassmatt** [comment]
The official docs have been published. We can complete this PR whenever.

**Comment by mahilleb-msft** [comment]
@vtbassmatt , @ericsciple - I'm looking for the "step reuse" content in docs.ms.com, do you have a link?
https://github.com/Microsoft/azure-pipelines-agent/blob/3d39fca3cac2bf54c16600e0a3b9e7972d4c5ef3/docs/preview/yamlgettingstarted-reusestep.md

**Comment by mahilleb-msft** [comment]
Oh, might have found it here https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=vsts#step-template.

**Comment by vtbassmatt** [comment]
That works for now. I have a pending PR to bring back the rest of the template stuff.

**Pull request merged**
