### PR TITLE
Add solution file for better building experience inside VS

### PR DESCRIPTION
**Pull request by kant2002**
- TargetFramework is nescessary inside project files, to be usable by VS even if MSBuild does not care
- Controlling of value inside TargetFramework possible via custom MSBuild property, but seems to be required renaming Common.props to Directory.Build.props

See #2611

### CODE REVIEW

**Comment by jtpetty** [comment]
@kant2002 - we consciously made the decision to pull out all the common properties into the Commons.prop in order to make it easier to maintain. I would prefer renaming Common.props to Directory.Build.props if that allows us to have one place to define these and have it work for VS.

How did you make the .sln file? Does it make sense to have a command in ./dev.sh that builds this .sln file rather than checking it in and maintaining it if the structure of the project changes?

**Comment by kant2002** [comment]
I probably was too tired. Just adding SLN file works pretty fine.

**Comment by kant2002** [comment]
Regarding second question: "Does it make sense to have a command in ./dev.sh that builds this .sln file rather than checking it in and maintaining it if the structure of the project changes?" I think it will be fine, but I do not aware about easy ways to generate solutions. Honestly, I do not care, since I think SLN files is default way to manage collection of projects in C# world. I see when somebody play with MSBuild files, but again, without VS supporting such scenarios, I do not believe it will be practical for external users. It just raise barrier for contributions.

**Comment by kant2002** [comment]
Can somebody like @alex-peck or @jtpetty take a look?

**Comment by kant2002** [comment]
Thanks

**Pull request merged**
