### PR TITLE
Updated to .NET Core 3.1

### PR DESCRIPTION
**Pull request by jtpetty**
Address #2668

### CODE REVIEW

**Comment by RobertDougan** [comment]
Hi @jtpetty, is there a timescale for this to be merged and released?

**Comment by jtpetty** [comment]
@RobertDougan  - Right now, we are trying to get a successful rollout of the agent with the currently checked in features. Once that is done and stable, we will merge in this change and release the agent with only these changes so that we can react quickly to any unintended behavior changes caused by moving to  .NET Core 3.1. I do not have a definitive time line yet, but I would expect the beginning of February.

**Comment by Zarshua** [comment]
Hey, I'm wondering if my issue is related to this thread...

I have a build that fails when using .NET Core 3.1.101 and .NET Standard 2.1

`
##[error]The nuget command failed with exit code(1) and error(NU1201: Project App.Client is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Project App.Client supports: netstandard2.1 (.NETStandard,Version=v2.1)
`

**Comment by jtpetty** [comment]
@Zarshua - This change was to how the agent itself is built and should not impact building a target project.

**Comment by Zarshua** [comment]
@jtpetty - thanks for the response. I opened another issue in the right place: https://github.com/microsoft/azure-pipelines-tasks/issues/12398

**Pull request merged**
