### PR TITLE
Add glob refs to agent

### PR DESCRIPTION
**Pull request by fadnavistanmay**
Add glob refs to agent

### CODE REVIEW

**Comment by TingluoHuang** [comment]
@tanmaymsft why we need this?

**Comment by geekstew** [comment]
> @tanmaymsft why we need this?
We need this because we've added globbing support for BDM and other clients and for that to work this nuget package needs to work.

**Comment by TingluoHuang** [comment]
why the agent need to carry that assembly? the agent itself doesn't need it.

**Comment by geekstew** [comment]
> why the agent need to carry that assembly? the agent itself doesn't need it.
We recently added globbing support that is in the VSO repo. The Build drop manager also uses this. What is the right way to go about adding this nuget package reference and please guide us as to where this needs to be added instead?

**Comment by mizho** [comment]
>           why the agent need to carry that assembly? the agent itself doesn't need it.

Ting - Maybe this is the wrong way to do it. This is needed by PipelineArtifact plugins. But I think we should add the deps into vsts-api pkg. However, Owen told me the generator tool is not working. How do we get this dep bundled into vsts-api pkg?

**Comment by bryanmacfarlane** [comment]
The agent is a generic step runner.  This PR has no context.  No issue, what's trying to be solved. etc...

**Comment by bryanmacfarlane** [comment]
create an issue stating the problem, what's needed and then we can discuss what needs to be done.

**Pull request closed without merging**
