### PR TITLE
Removed branch creation from fetch by commit id

### PR DESCRIPTION
**Pull request by IlyaChistov**
After discussing this issue (#3180) with @jeschu1 she suggested that when fetching by commit id we dont need to create a branch with the same name, so I removed the destination from the refspec.

### CODE REVIEW

**Comment by jeschu1** [comment]
@IlyaChistov can you show me what the output looks like from the agent log?  I just want to double check it does exactly what i'm thinking.  Thank You!

**Comment by IlyaChistov** [comment]
@jeschu1 
[Worker_20210525-100316-utc.log](https://github.com/microsoft/azure-pipelines-agent/files/6538518/Worker_20210525-100316-utc.log)

**Review by jeschu1 — APPROVED** [review]

**Review by MaximMalygin — APPROVED** [review]

**Review by MaximMalygin — APPROVED** [review]

**Review by anatolybolshakov — APPROVED** [review]

**Pull request merged**
