### PR TITLE
fix: solving download secure files

### PR DESCRIPTION
**Pull request by phmonte**
[Issue](https://github.com/microsoft/azure-pipelines-agent/issues/4962)

### CODE REVIEW

**Comment by RafaelPlantard** [comment]
Any news in merging this?

**Comment by mmrazik** [comment]
The original issue was mitigated by turning off a feature flag. We will look into a proper fix (as well as some repair items on our end to prevent regressions like this).

**Comment by mmrazik** [comment]
Thank you @phmonte!

**Comment by phmonte** [comment]
@mmrazik I'll close the PR then, thanks.

**Pull request closed without merging**
