### PR TITLE
Removed NPM module and executable which comes with NodeJS fox non windows distribution

### PR DESCRIPTION
**Pull request by mpodriezov**
The NPM and its dependencies, which are bundled with NodeJS 6 and 10, have a lot of vulnerabilities and had generated a lot of component governance bugs recently. When we layout the agent we copy NodeJS the files from https://nodejs.org/dist/v6.17.1 and put them into _externals folder. Along with NodeJS executable we copy node package manager (NPM).

The NPM resides in the _externals/node/bin  folder and its dependies are in inside _external/node/lib/node_modules folder. The NPM is not being used by the agent and can be removed. The agent version for  windows doesn't include the NPM in the current version. By removing the NPM and it's node modules, not only we will make versions to be more consistent, but also fix potential component governance bugs in the future.

### CODE REVIEW

**Review by vtbassmatt — COMMENTED** [review]
I've been away from the ecosystem too long to know whether this is safe or not. Double-check what the Node ecosystem tasks (like [Npm](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/NpmV1) and [UseNode](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/UseNodeV1)) expect, and whether this will be a breaking change for self-hosted agents. Also double check whether the hosted agents bring along a copy of `npm` or if they rely on the agent having it. After that, it's prrrrrrrrobably safe...

**Comment by mpodriezov** [comment]
Thanks for the feedback Matt.

1. Regarding [ task UseNode](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/node-js). It doesn't use the pre-installed npm (old 3.x) in any way. The task is actually installing NodeJS version into _work/tools directory and adjusts PATH so next tasks can use that version of nodejs. That's probably what people mostly do when they need to build/run anything and we also suggest to use this task directly in yaml templates. 

2. Regarding [NPM task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/npm). The task runs like in a "box". I logged which NodeJS version is used to run it and it was v10 (I modified the code of the task locally so it logs `process.version` variable and ran a pipeline). The tasks can call NPM commands (based on is defined in yaml) and when it needs to do that [it spawns a new process](https://github.com/microsoft/azure-pipelines-task-lib/blob/5ebf55f67908c5b16314ccb60a0c6b94dacd8a0a/node/toolrunner.ts#L1014
). That process can use another NodeJS/NPM.
The tasks also demands NPM to be installed on VM and we also make [it clear in the public docs ](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/npm?view=azure-devops#demands).
I made a test using current pipelines-agent for linux (not modified). I created a pipeline with that task and it failed for my local agent, because the NPM was not installed. Then I added UseNode before and it worked fine. 

3. Our hosted MMS agents come with pre-installed LTS nodejs and NPM, so [NPM task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/npm?view=azure-devops) won't fail even without using [UseNode task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/node-js). We tested this by creating a pipeline which just logs `node -v` and `npm -v`. 

4. There are also [Grunt](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/grunt) and [Gulp](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/gulp) tasks. Both are regular node packages you install with NPM. Those will run out of the box in MMS agents without any problem, but hosted agents need to use [UseNode task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/node-js) before anyway. They don't use pre-installed nodejs or npm.

@mmrazik  @TomasHubelbauer  What else can I test?

**Review by mmrazik — APPROVED** [review]

**Review by anatolybolshakov — APPROVED** [review]
LGTM, thanks!

**Review by TomasHubelbauer — APPROVED** [review]
LGTM 👍

**Comment by DenisRumyantsev** [comment]
Please do not merge this PR until I complete testing it.

**Comment by mpodriezov** [comment]
> Please do not merge this PR until I complete testing it.

Yes. I want to be careful here. What test scenarios do you do?

**Comment by DenisRumyantsev** [comment]
@mpodriezov I am just double-checking if there are any possible cases when npm is used by the agent, or by tasks, or in our CI, or somewhere else

**Comment by DenisRumyantsev** [comment]
@mpodriezov LGTM, tested these changes end-to-end manually for Linux.
The agent works fine without npm. Checked that the agent does not use npm anywhere during tasks execution.
Also, here are tests that check if node exists: [src/Test/L0/NodeHandlerL0.cs](https://github.com/microsoft/azure-pipelines-agent/blob/master/src/Test/L0/NodeHandlerL0.cs) ([line 37](https://github.com/microsoft/azure-pipelines-agent/blob/192573eaaffd5e3c0c146c943956e5f130af3bbb/src/Test/L0/NodeHandlerL0.cs#L37), [line 62](https://github.com/microsoft/azure-pipelines-agent/blob/192573eaaffd5e3c0c146c943956e5f130af3bbb/src/Test/L0/NodeHandlerL0.cs#L62), [line 91](https://github.com/microsoft/azure-pipelines-agent/blob/192573eaaffd5e3c0c146c943956e5f130af3bbb/src/Test/L0/NodeHandlerL0.cs#L91), [line 125](https://github.com/microsoft/azure-pipelines-agent/blob/192573eaaffd5e3c0c146c943956e5f130af3bbb/src/Test/L0/NodeHandlerL0.cs#L125), [line 155](https://github.com/microsoft/azure-pipelines-agent/blob/192573eaaffd5e3c0c146c943956e5f130af3bbb/src/Test/L0/NodeHandlerL0.cs#L155)).
There are no tests that check if npm exists. Npm can be removed.

**Review by DenisRumyantsev — APPROVED** [review]

**Comment by DenisRumyantsev** [comment]
Checklist:
* [x] Checked that npm is not used anywhere in the agent source code
* [x] Checked that there are no tests that npm exists in the `externals` agent folder
* [x] Checked that the modified `externals.sh` script is executed only during the `dev.sh` script execution, and the `dev.sh` script is executed only while building the agent
* [x] Agent was successfully built for all platforms
* [x] Linux agent was successfully configured
* [x] Linux agent runs jobs and executes tasks successfully (using the `node` tool from the `externals` agent folder)

**Review by alexander-smolyakov — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
