### PR TITLE
Make tarring default for Pipeline Caching and modifying Display to Info from Warning for Save Cache

### PR DESCRIPTION
**Pull request by fadnavistanmay**
To make tarring by default for Pipeline Caching.

### CODE REVIEW

**Comment by fadnavistanmay** [comment]
@johnterickson / @owenhuynMSFT - PR to make tarring default.

**Comment by johnterickson** [comment]
@fadnavistanmay How do you plan to test this before rollout?

**Comment by fadnavistanmay** [comment]
> @fadnavistanmay How do you plan to test this before rollout?

Currently, hooking up private agent to build canary builds and test the behavior. Do you have anything specific in mind?

**Comment by johnterickson** [comment]
Can you point me to the test runs?

**Comment by johnterickson** [comment]
Also, how does one revert to previous behavior - and can you double-check that it works?

**Comment by fadnavistanmay** [comment]
> Also, how does one revert to previous behavior - and can you double-check that it works?

Test runs - https://buildcanary.visualstudio.com/CacheSandbox/_build?definitionId=3463

The previous behavior would to be explicitly set, AZP_CACHING_CONTENT_FORMAT = Files, tested it works. :)

**Comment by johnterickson** [comment]
> > Also, how does one revert to previous behavior - and can you double-check that it works?
> 
> Test runs - https://buildcanary.visualstudio.com/CacheSandbox/_build?definitionId=3463 . We will modify the test runs after agent releases with this change.
> 
> The previous behavior would to be explicitly set, AZP_CACHING_CONTENT_FORMAT = Files, tested it works. :)

Thanks! Good to have listed here in case someone is impacted.

**Comment by johnterickson** [comment]
If I change the env var, it changes the key, right?

**Comment by fadnavistanmay** [comment]
> If I change the env var, it changes the key, right?

I think we had decided against it, and added a new field for content format.

**Comment by jabbera** [comment]
I think this breaks windows that doesn't have tar in it's path:

https://github.com/microsoft/azure-pipelines-agent/issues/2595

**Comment by damccorm** [comment]
@fadnavistanmay @owenhuynMSFT @johnterickson could you take a look?

**Comment by jabbera** [comment]
We are working this in the other issue!

**Pull request merged**
