### PR TITLE
Bumped Net Core version to latest patch (SDK - 3.1.409, runtime - 3.1.15)

### PR DESCRIPTION
**Pull request by anatolybolshakov**
Bumped Net Core version to latest patch at the moment.
This should fix several issues like https://github.com/microsoft/azure-pipelines-agent/issues/3093

Testing changes: done.

### CODE REVIEW

**Comment by EzzhevNikita** [comment]
@anatolybolshakov It is required to update several packages in the agent feed according to the new versions of sdk and runtime

**Comment by anatolybolshakov** [comment]
Looks like there is no Net core SDK 3.1.409 binaries for RHEL6 - I asked Net core team in https://github.com/dotnet/core/issues/5989 to check if it's expected.

**Comment by anatolybolshakov** [comment]
Freezed this PR at the moment - until we have a plan to move RHEL 6 out of support.

**Comment by KonstantinTyukalov** [comment]
Closing this because we're planning to migrate the agent to .net 6 - https://github.com/microsoft/azure-pipelines-agent/issues/3922

**Pull request closed without merging**
