### PR TITLE
Support compiling for arm64

### PR DESCRIPTION
**Pull request by qmfrederik**
This updates the build scripts and allow you to compile on arm64 hardware (such as the Raspberry Pi 4).
Essentially #1921 / #2256 redone for the current state of master.

### CODE REVIEW

**Comment by jtpetty** [comment]
@vtbassmatt - What are your thoughts on supporting ARM64?

**Comment by vtbassmatt** [comment]
@jtpetty I want to do it but we have to be on .NET Core 3 first. ([2.1 does not support ARM64](https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1-supported-os.md) while [3.0+ does](https://github.com/dotnet/core/blob/master/release-notes/3.0/3.0-supported-os.md).) We probably should go to 3.1 at this point since it's an LTS.

**Comment by qmfrederik** [comment]
@vtbassmatt Correct, this PR makes more sense when you're on .NET Core 3.1.

I could update #2616 so that it targets .NET Core 3.1. Would that work for you?

**Comment by vtbassmatt** [comment]
@qmfrederik thanks for the offer. I've prototyped upgrading us to 3.0, and the PR was pretty smooth sailing. However, we've had behavior regressions in the past when upgrading .NET Core major versions, so I want to make sure my team is intimately familiar with the details when we do so. (That's a long way of saying, we'll handle the framework upgrade, and then we can figure out how best to get ARM64 support.)

**Comment by qmfrederik** [comment]
That’s fine. Meanwhile, could you consider upgrading to the latest 2.1.x release? It improves OS support (mainly by adding support for OpenSSL 1.1, which is used by e.g. newer Ubuntu versions).

**Comment by vtbassmatt** [comment]
Yeah, I saw the other PR and we're considering that one right now.

**Comment by damccorm** [comment]
Hey @qmfrederik - I'm going to close here since we did this in #2881. If you think that's wrong we can reopen here.

**Pull request closed without merging**
