### PR TITLE
Filling publish script with hashes

### PR DESCRIPTION
**Pull request by DaniilShmelev**
We need to provide `HashValue` argument to each `Add-DistributedTaskPackage` call in the agent publish script. We've decided to make this script a template and fill it in the release pipeline along with `InstallAgentPackage.xml`.
This script will now be stored in the `tfs/m<SPRINT_VERSION>/PipelinesAgentRelease/<AGENT_VERSION>/Publish.ps1`.
These changes will be pushed to the `AzureDevOps.ConfigChange` repo.

### CODE REVIEW

**Comment by DaniilShmelev** [comment]
Test pipeline: https://dev.azure.com/mseng/AzureDevOps/_build/results?buildId=15944470
Auto-generated PR to the config change repo: https://dev.azure.com/mseng/AzureDevOps/_git/AzureDevOps.ConfigChange/pullrequest/629027

**Review by mjroghelia — APPROVED** [review]

**Review by anatolybolshakov — APPROVED** [review]
LGTM, thanks for adding this!

**Review by alexander-smolyakov — APPROVED** [review]
LGTM! Thanks for doing this!

**Review by DenisRumyantsev — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
