### PR TITLE
Fixed result for MergeTrackingConfigs

### PR DESCRIPTION
**Pull request by anatolybolshakov**
MergeTrackingConfigs takes previousConfig and newConfig, and performs merging (results are saved in newConfig).
Previously there was previousConfig being returned - changed to newConfig.

Testing: checked with TFVC, Git repositories - works fine.

### CODE REVIEW

**Comment by jessehouwing** [comment]
An explicit folder mapping will still break things I'm guessing...

$/Project/Something/That/Must/Be/In/A/Fixed/Location => c:\myspeciallocation\

**Review by alexander-smolyakov — APPROVED** [review]

**Review by max-zaytsev — APPROVED** [review]

**Comment by anatolybolshakov** [comment]
> An explicit folder mapping will still break things I'm guessing...
> 
> ```
> $/Project/Something/That/Must/Be/In/A/Fixed/Location => c:\myspeciallocation\
> ```

Thanks for the point! You can map the same server folder in more that one workspace per [docs](https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/optimize-your-workspace?view=azure-devops#use-workspaces-to-isolate-and-manage-work-among-different-branches) - so there should not be similar issue for this case.

**Comment by jessehouwing** [comment]
Yes, you can map the same server folder multiple times, but you can't explicitly map the same local folder multiple times.

When you map to say 

```
C:/inetpub/wwwroot
```

Thus explicitly outside if the sourcesfolder, the same issue will still appear as long as machines share the same hostname.

This is perfectly valid for tfvc

**Comment by anatolybolshakov** [comment]
> Yes, you can map the same server folder multiple times, but you can't explicitly map the same local folder multiple times.
> 
> When you map to say
> 
> ```
> C:/inetpub/wwwroot
> ```
> 
> Thus explicitly outside if the sourcesfolder, the same issue will still appear as long as machines share the same hostname.
> 
> This is perfectly valid for tfvc

сс @MaximMalygin

**Comment by MaximMalygin** [comment]
> Yes, you can map the same server folder multiple times, but you can't explicitly map the same local folder multiple times.
> 
> When you map to say
> 
> ```
> C:/inetpub/wwwroot
> ```
> 
> Thus explicitly outside if the sourcesfolder, the same issue will still appear as long as machines share the same hostname.
> 
> This is perfectly valid for tfvc

Exactly, and  this PR fixed this problem, we've got the same local folder for TFVC because we always return previousconfig in merge function, but logic to create new source folder already exists here, for tfvc we created bulid directory with AgentID

https://github.com/microsoft/azure-pipelines-agent/blob/65d7378c42a891aace0ebbb0615ca00d5179ebaa/src/Agent.Worker/Build/TrackingManager.cs#L98

and execute TrackingConfig where all folder depend on our AgentId

https://github.com/microsoft/azure-pipelines-agent/blob/b93f8f1f4e53ddf5d9cd25090db6f71b092d177c/src/Agent.Worker/Build/TrackingConfig.cs#L82

but previously we returned back to previous directory in  MergeTrackingConfigs function
https://github.com/microsoft/azure-pipelines-agent/blob/65d7378c42a891aace0ebbb0615ca00d5179ebaa/src/Agent.Worker/Build/TrackingManager.cs#L124

**Pull request merged**
