### PR TITLE
Update dotnet install script

### PR DESCRIPTION
**Pull request by alexander-smolyakov**
This PR provides an update to the following scripts:
- src/Misc/dotnet-install.ps1 (Taken from https://dot.net/v1/dotnet-install.ps1)
- src/Misc/dotnet-install.ps1 (Taken from https://dot.net/v1/dotnet-install.sh)

### CODE REVIEW

**Review by EzzhevNikita — APPROVED** [review]

**Review by max-zaytsev — APPROVED** [review]

**Comment by EzzhevNikita** [comment]
@alexander-smolyakov It looks like dotnet-install.sh script is causing test failures on Mac and Linux

**Comment by alexander-smolyakov** [comment]
@EzzhevNikita, It seems the issue related to the script itself.
I found the related issue: https://github.com/dotnet/install-scripts/issues/136
As I can see, the script was already fixed in this PR: https://github.com/dotnet/install-scripts/pull/137
So now we have to wait until the fixed version of the script will be published on the site.

**Comment by alexander-smolyakov** [comment]
Fix was published. All CI checks are passed now.

**Comment by alexander-smolyakov** [comment]
@damccorm, could you please take a look at this PR?

**Review by anatolybolshakov — APPROVED** [review]

**Review by damccorm — APPROVED** [review]

**Pull request merged**
