### PR TITLE
Summarized view of Xunit hierarchal tests based on a FF

### PR DESCRIPTION
**Pull request by upadhyayap**
### What are you trying to accomplish?
Getting control to enable/disable summarized view of xunit hierarchal test results

### What approach did you choose and why?
Using an already present FF for a summarized view of xunit hierarchal test results.

### What should reviewers focus on?
Since this is my first PR, please look if this change is not going to break any intended scenario.

### If something goes wrong, what are the mitigation strategies?
Can be controlled by TestManagement.PublishTestResultsTask.EnableXUnitHeirarchicalParsing FF 

### Performance Impact

N/A

### Observability

N/A

### CODE REVIEW

**Review by navin22 — APPROVED** [review]

**Review by anatolybolshakov — APPROVED** [review]

**Review by alexander-smolyakov — APPROVED** [review]

**Review by DaniilShmelev — APPROVED** [review]

**Comment by DaniilShmelev** [comment]
@upadhyayap looks like `PublishTrxResults` unit test is failing. Could you please take a look?

**Comment by upadhyayap** [comment]
> @upadhyayap looks like `PublishTrxResults` unit test is failing. Could you please take a look?

pushed a commit to fix the failing test

**Pull request merged**
