### PR TITLE
Added Oracle Linux 7+ to supported os

### PR DESCRIPTION
**Pull request by tgwbean**
#4941: Added Oracle Linux 7+ to supported os for net6

### CODE REVIEW

**Comment by tgwbean** [comment]
@ismayilov-ismayil, @lareeth, @DergachevE, @kirill-ivlev, @vmapetr: Anyone of you care to check this?

**Comment by lareeth** [comment]
@tgwbean Unfortunately I am not a maintainer, so am unable to help, sorry.

**Review by ismayilov-ismayil — APPROVED** [review]

**Comment by tgwbean** [comment]
Hello @ismayilov-ismayil, thanks for approving the PR. Can you please add a label to the PR (I'm not allowed to do that)?

Thanks!

**Comment by DenisRumyantsev** [comment]
These changes were merged in another PR mentioned right above, so I close this PR.

**Pull request closed without merging**
