### PR TITLE
Update NODE10_VERSION to 10.24.1 #3376

### PR DESCRIPTION
**Pull request by DalpheSDC**
Update NODE10_VERSION to 10.24.1 #3376

### CODE REVIEW

**Comment by DalpheSDC** [comment]
Please make a review of the change and approve it
@mjroghelia, @anatolybolshakov and @EzzhevNikita

**Review by mjroghelia — APPROVED** [review]
@anatolybolshakov LGTM. I'm going to leave it to you to merge these.

**Review by EzzhevNikita — APPROVED** [review]

**Review by max-zaytsev — APPROVED** [review]

**Review by anatolybolshakov — APPROVED** [review]

**Pull request merged**
