### PR TITLE
Added ability to download artifacts from canceled builds.

### PR DESCRIPTION
**Pull request by srbrills**
Due to recent changes in the multi-stage pipelines, it may sometimes be necessary to download artifacts from builds that have an overall status of "canceled".  Sometimes canceled builds may have had one or more stages that were successful or partially successful, but there is currently no way to skip an unnecessary stage without marking it as "canceled", which in turn marks the entire run as "canceled".  It would really help if downstream pipelines were allowed to retrieve artifacts from canceled pipeline runs for this reason.

- Added ability to download artifacts from canceled builds.

### CODE REVIEW

**Comment by mjroghelia** [comment]
@b-barthel @fadnavistanmay What do y'all think of this?

**Comment by fadnavistanmay** [comment]
> @b-barthel @fadnavistanmay What do y'all think of this?

It should be fine, I think. The only issue I can think of is I am not sure if Pipelines make a call to delete the artifacts if the build is cancelled, my hunch is, it should. Let me get back to you on this.

**Comment by fadnavistanmay** [comment]
> > @b-barthel @fadnavistanmay What do y'all think of this?
> 
> It should be fine, I think. The only issue I can think of is I am not sure if Pipelines make a call to delete the artifacts if the build is cancelled, my hunch is, it should. Let me get back to you on this.

Actually, looks like we already allow failedbuilds, should be good.

**Review by fadnavistanmay — APPROVED** [review]

**Comment by mjroghelia** [comment]
Thanks for the contribution @srbrills. Thanks for the review @fadnavistanmay.

**Pull request merged**
