### PR TITLE
Fix: Remove invalid chars from filename

### PR DESCRIPTION
**Pull request by mihaiandreiratoiu**
## Problem
When using the disableLogUploads flag the agent will include the step name in the file. 
The step name isn't sanitized.
A step name which has a slash in it "Step name/ something" will be interpreted as a directory thus failing the pipeline.
Also, the user can craft a step name using a structure  "../../../file" allowing him to escape the build context
This error appeared on linux self-hosted agent

## Update
On the windows agent the issue is even worse, the user must not have : also in the path

## Fix 
Used a regex to replace every invalid character from the name before passing it as a path
I've used the same syntax as in another file from this repository. (ReleaseJobExtension.cs:352-354)

### CODE REVIEW

**Comment by mihaiandreiratoiu** [comment]
Can anyone take a look at this? @KonstantinTyukalov

**Comment by mihaiandreiratoiu** [comment]
Hello, any updates on this @KonstantinTyukalov ? I saw that you added the enhancement tag. I feel it's more of a bug/security issue than an enhancement

**Comment by KonstantinTyukalov** [comment]
Hi @mihaiandreiratoiu, thanks for contributing! This PR is in the review queue, we'll check it soon

**Review by KonstantinTyukalov — APPROVED** [review]
LGTM, thanks!

**Review by vmapetr — APPROVED** [review]

**Review by kirill-ivlev — APPROVED** [review]

**Review by PavloAndriiesh — APPROVED** [review]

**Pull request merged**
