### PR TITLE
Fix event logs dumping

### PR DESCRIPTION
**Pull request by max-zaytsev**
Changes:

- Fixed `StartTime` and `EndTime` formats to filter event logs correctly regardless of regional format when collecting diagnostic logs.
Related issue: https://github.com/microsoft/azure-pipelines-agent/issues/3792
- Changed file extension to .csv to make log analysis more convenient in further investigations.

More info about [The universal sortable ("u") format specifier](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings#the-universal-sortable-u-format-specifier)

Tested manually:
Ran the pipeline PC set to a regional format "English (Australia)" and "English (United States)"

### CODE REVIEW

**Review by AndreyIvanov42 — APPROVED** [review]

**Review by anatolybolshakov — APPROVED** [review]
LGTM, thanks! Could you please also reflect other changes in description (like changing of filename extension)?

**Review by KonstantinTyukalov — APPROVED** [review]

**Comment by max-zaytsev** [comment]
@mmrazik  Could you please take a look at this?

**Review by mmrazik — APPROVED** [review]

**Pull request merged**
