### PR TITLE
Update VssApiVersion to 0.5.170-private

### PR DESCRIPTION
**Pull request by kutsen99**
Make dedup redirect timeout configurable (!627856)
Default dedup redirect timeout is 1 minute. Make it configurable by VSO_DEDUP_REDIRECT_TIMEOUT_IN_SEC

### CODE REVIEW

**Review by anatolybolshakov — APPROVED** [review]

**Comment by Manoj496** [comment]
Hi,

We've build agent version : 2.187.2. From past two weeks all our pipelines are facing issue downloading chocolatey. It says path is denied. Is it something do with updating build agents?

**Pull request merged**
